cart/urls.py
from django.conf.urls import url
from . import views

app_name = 'cart'

urlpatterns = [
    url(r'^$', views.cart_detail, name='cart_detail'),
    url(r'^add/(?P<produto_id>\d+)/$', views.cart_add, name='cart_add'),
    url(r'^remove/(?P<produto_id>\d+)/$', views.cart_remove, name='cart_remove'),
]

materiais/urls.py
from django.conf.urls import url
from django.urls import path
from rest_framework.urlpatterns import format_suffix_patterns

from materiais import views
from materiais.views import PedidoWebTradicionalList, PedidoWebTradicionalDetalhe, \
    PedidoWebTradicionalUpdate, ProdutoDetalhe, ProdutoCreate, ProdutoList, manage_pedidowebitem

app_name = 'materiais'

urlpatterns = [
    
    # Pedido Tipo: Tradicional
    url(r'^pedidoweb_list/$', PedidoWebTradicionalList.as_view(), name='pedidoweb_list'),
    url(r'^pedidoweb_list/(?P<pk>[0-9]+)/$', PedidoWebTradicionalDetalhe.as_view(), name="pedidoweb_detail"),
    url(r'^pedidoweb_edit/(?P<pk>[0-9]+)/edit/$', PedidoWebTradicionalUpdate.as_view(), name='pedidoweb_edit'),
    
    url(r'^manage_pedidowebitem/(?P<pk>[0-9]+)/$', manage_pedidowebitem, name='manage_pedidowebitem'),

    
    url(r'^create/$', views.order_create, name='order_create'),
    # Pedido Tipo: E-Commerce
    # url(r'', views.ProdutoList.as_view(), name='produto_list'),
    url(r'^produto_list/$', ProdutoList.as_view(), name='produto_list'),
    url(r'^produto_list/(?P<categoria_slug>[-\w]+)/$', ProdutoList.as_view(), name='produto_list_by_category'),
    # url(r'^(?P<id>\d+)/(?P<slug>[-\w]+)/$', views.produto_detail, name='produto_detail'),
    url(r'^produto_list/(?P<id>\d+)/(?P<slug>[-\w]+)/$', views.produto_detail, name='produto_detail'),
    url(r'^produto_detalhe/(?P<pk>[0-9]+)/$', ProdutoDetalhe.as_view(), name="produto_detalhe"),
    url(r'^produto_add/$', ProdutoCreate.as_view(), name='produto_add'),

    # Index
    path('', views.ProdutoList.as_view(), name='home'),

    # Search PedidoWeb
    url(r'^search_pedidoweb/$', views.search_pedidoweb, name='search_pedidoweb'),


]

urlpatterns = format_suffix_patterns(urlpatterns)

usesoft_R3/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.contrib.auth.views import password_reset, password_reset_done, password_reset_confirm, \
    password_reset_complete
from django.urls import path, include
from rest_framework import routers
from rest_framework.schemas import get_schema_view

from accounts.views import login_view, logout_view
from django.conf.urls.static import static
from usesoft_R3 import settings

from materiais import api_views as materiais_api
from globais import api_views as globais_api
from financeiro import api_views as financeiro_api
from faturamento import api_views as faturamento_api
from accounts import api_views as accounts_api

from rest_framework.schemas import get_schema_view

schema_view = get_schema_view(title='Usesoft_R3 API',
                              url='https://central-aluminio.herokuapp.com/api/')

router = routers.DefaultRouter()
router.register(r'usuarios', accounts_api.UserViewSet)
router.register(r'grupos', accounts_api.GroupViewSet)
router.register(r'participantes', faturamento_api.ParticipanteViewSet)
router.register(r'gruposparticipantes', faturamento_api.GrupoParticipanteViewSet)
router.register(r'regioesdevenda', faturamento_api.RegiaoDeVendaViewSet)
router.register(r'tipospagamento', financeiro_api.TipoPagamentoViewSet)
router.register(r'prazospagamento', financeiro_api.PrazoPagamentoViewSet)
router.register(r'tiposdocumentos', financeiro_api.TipoDocumentoViewSet)
router.register(r'cfops', globais_api.CfopViewSet)
router.register(r'codigosncm', globais_api.CodigoNcmViewSet)
router.register(r'municipios', globais_api.MunicipioViewSet)
router.register(r'estados', globais_api.UfViewSet)
router.register(r'paises', globais_api.PaisIbgeViewSet)
router.register(r'mensagenspadrao', globais_api.MensagemPadraoViewSet)
router.register(r'tiposoperacoesfiscais', globais_api.TipoOperacaoFiscalViewSet)
router.register(r'pedidosweb', materiais_api.PedidoWebViewSet)
router.register(r'pedidowebitens', materiais_api.PedidoWebItemViewSet)
router.register(r'categorias', materiais_api.CategoriaViewSet)
router.register(r'produtos', materiais_api.ProdutoViewSet)

urlpatterns = [
    url(r'^schema/$', schema_view),
    url(r'^api/', include(router.urls)),
    url(r'^api-auth/', include('rest_framework.urls'),),
    path('admin/', admin.site.urls),
    url(r'^cart/', include('cart.urls')),
    url(r'^faturamento/', include('faturamento.urls')),
    url(r'^financeiro/', include('financeiro.urls')),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^', include('materiais.urls')),
    url(r'^login', login_view, name='login'),
    url(r'^logout', logout_view, name='logout'),
    # url(r'^change-password', change_password, name='change_password'),
    url(r'^reset-password/$', password_reset, name='reset_password'),
    url(r'^reset-password/done/$', password_reset_done, name='password_reset_done'),
    url(r'^reset-password/confirm/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        password_reset_confirm, name='password_reset_confirm'),
    url(r'^reset-password/complete/$', password_reset_complete, name='password_reset_complete'),



    ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/models.py
from django.db import models

# Create your models here.

cart/forms.py
from django import forms


PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 101)]
DESCONTO_CHOICES = [(i, str(i)) for i in range(0, 31)]


class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(label='Quantidade', choices=PRODUCT_QUANTITY_CHOICES, coerce=int)
    update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)
    desconto = forms.TypedChoiceField(choices=DESCONTO_CHOICES, coerce=int, required=False)
    preco_negociado = forms.DecimalField(label='Preço Líquido', decimal_places=2, required=False, initial=True)

cart/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST

from materiais.models import Produto
from .cart import Cart
from .forms import CartAddProductForm


@require_POST
def cart_add(request, produto_id):
    cart = Cart(request)
    produto = get_object_or_404(Produto, id=produto_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data

        if cd['update'] is False:
            if cd['desconto'] > 0:
                desconto = cd['desconto']
            else:
                # =100-((PREÇO_SUGERIDO*100)/PREÇO_VENDA)
                desconto = 100 - ((cd['preco_negociado']*100) / produto.preco_venda)

            if desconto <= 30:
                cart.add(produto=produto,
                         quantity=cd['quantity'],
                         preco_negociado=cd['preco_negociado'],
                         update_quantity=cd['update'],
                         desconto=desconto)
                messages.success(request, 'Produto ' + produto.produto + produto.descricao + ' colocado no carrinho.')
            else:
                messages.error(request, 'O produto '+str(produto.produto)+' com preço de venda R$ ' +
                               str(produto.preco_venda)+' e preço negociado a R$' +
                               str(cd['preco_negociado']))
                messages.error(request, 'Gerou um percentual de desconto de '+str(desconto) +
                               '% que está acima do limite máximo permitido ')
                messages.error(request, 'Por esse motivo, o produto não foi colocado no carrinho.')
        else:
            cart.add(produto=produto,
                     quantity=cd['quantity'],
                     preco_negociado=cd['preco_negociado'],
                     update_quantity=cd['update'],
                     desconto=cd['desconto'])

    return redirect('cart:cart_detail')


@login_required
def cart_remove(request, produto_id):
    cart = Cart(request)
    produto = get_object_or_404(Produto, id=produto_id)
    cart.remove(produto)
    messages.success(request, 'Produto ' + produto.produto + produto.descricao + ' removido do carrinho.')

    return redirect('cart:cart_detail')


@login_required
def cart_detail(request):
    cart = Cart(request)
    for item in cart:
        item['update_quantity_form'] = CartAddProductForm(
            initial={'quantity': item['quantity'],
                     'preco_negociado': item['preco_unitario'],
                     'update': True,
                     'perc_desc':
                         100.00 - ((float(item['preco_unitario'])*100)/float(item['price'])),
                     # 'perc_desc': item['perc_desc'],
                     'valor_desconto':
                     (item['price'] * (item['perc_desc']/100)) *
                     item['quantity']
                     })
    return render(request, 'cart/detail.html', {'cart': cart})

cart/templates/cart/detail.html
{% extends "materiais/base.html" %}

{% block title %}
    Seu carrinho de compras
{% endblock %}

{% block content %}

        {% if messages %}
            <div class="success">
                <ul class="messages">
                    {% for message in messages %}
                        <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                    {% endfor %}
                </ul>
            </div>
        {% endif %}

    <div class="d-block">

    {% if cart %}

       <p class="text-right">
            <a href="{% url 'materiais:produto_list' %}" class="btn btn-outline-success" role="button">Continuar vendendo</a>
            <a href="{% url 'materiais:order_create' %}" class="btn btn-outline-success" role="button">Fechar Pedido</a>
       </p>

        <h5><i class="fas fa-arrow-alt-circle-down"></i> Itens no seu carrinho de compras <i class="fas fa-arrow-alt-circle-down"></i></h5>

        <div class="row">
            {% for item in cart %}
                {% with produto=item.product %}

                     <div class="col-sm-12">
                          <div class="card border-success mb-3" style="background-color: #eee;">
                               <div class="card-body">
                                   <h6 class="card-title">{{ produto.produto }}</h6>
                                   <p class="card-text">{{ produto.descricao|capfirst }}</p>
                                   <p class="card-text">
                                        <form action="{% url 'cart:cart_add' produto.id %}" method="post">
                                            Quantidade: {{ item.update_quantity_form.quantity }}
                                            {{ item.update_quantity_form.update }}
                                            <input type="submit" value="Atualizar">
                                            <i class="fas fa-wrench"></i>
                                            {% csrf_token %}
                                        </form>
                                   </p>

<!--
                                   <p class="card-text">Preço de Venda: R$ {{ item.price|floatformat:2 }}</p>
                                   <p class="card-text">Percentual de Desconto: {{ item.perc_desc|floatformat:4 }}%</p>
                                   <p class="card-text">Valor do Desconto: R$ {{ item.valor_desconto|floatformat:2 }}</p>
-->
                                   <p class="card-text">Preço Líquido: R$ {{ item.total_price|floatformat:2 }}</p>

                                    <a href="{% url 'cart:cart_remove' produto.id %}">Remover <i class="fas fa-trash-alt"></i></a>
                               </div>
                          </div>
                     </div>

                {% endwith %}
            {% endfor %}
        </div>

    {% else %}

        <h1 align="center"><i class="fas fa-shopping-cart"></i> Seu carrinho está vazio!</h1>
        <a href="{% url 'materiais:produto_list' %}" class="btn btn-success btn-lg btn-block" role="button">Continuar vendendo!</a>

    {% endif%}
    </div>
{% endblock %}

cart/templates/cart/detail_backup.html
{% extends "materiais/base.html" %}
{% load static %}

{% block title %}
    Seu carrinho de compras
{% endblock %}

{% block content %}

        {% if messages %}
            <div class="success">
                <ul class="messages">
                    {% for message in messages %}
                        <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                    {% endfor %}
                </ul>
            </div>
        {% endif %}

    <div class="d-block">

    {% if cart %}

       <p class="text-right">
            <a href="{% url 'materiais:produto_list' %}" class="btn btn-outline-success" role="button">Continuar vendendo</a>
            <a href="{% url 'materiais:order_create' %}" class="btn btn-outline-success" role="button">Fechar Pedido</a>
       </p>

        <h1><i class="far fa-arrow-alt-circle-down"></i>Itens no seu carrinho de compras<i class="far fa-arrow-alt-circle-down"></i></h1>

        <div class="row">
            {% for item in cart %}
                {% with produto=item.product %}

                     <div class="col-sm-3">
                          <div class="card border-success mb-3" style="background-color: #eee;">
                               <div class="card-body">
                                   <h6 class="card-title">{{ produto.produto }}</h6>
                                   <p class="card-text">{{ produto.descricao|capfirst }}</p>
                                   <p class="card-text">
                                        <form action="{% url 'cart:cart_add' produto.id %}" method="post">
                                            Quantidade: {{ item.update_quantity_form.quantity }}
                                            {{ item.update_quantity_form.update }}
                                            <input type="submit" value="Atualizar">
                                            <i class="fas fa-wrench"></i>
                                            {% csrf_token %}
                                        </form>
                                   </p>

                                   <p></p>
<!--
                                   <p class="card-text">Preço de Venda: R$ {{ item.price|floatformat:2 }}</p>
                                   <p class="card-text">Percentual de Desconto: {{ item.perc_desc|floatformat:4 }}%</p>
                                   <p class="card-text">Valor do Desconto: R$ {{ item.valor_desconto|floatformat:2 }}</p>
-->
                                   <p class="card-text">Preço Líquido: R$ {{ item.total_price|floatformat:2 }}</p>

                                    <a href="{% url 'cart:cart_remove' produto.id %}">Remover </a>
                               </div>
                          </div>
                     </div>

                {% endwith %}
            {% endfor %}
        </div>

    {% else %}

        <h1 align="center"><i class="fas fa-shopping-cart"></i> Seu carrinho de compras está vazio!</h1>
        <a href="{% url 'materiais:produto_list' %}" class="btn btn-success btn-lg btn-block" role="button">Continuar vendendo!</a>

    {% endif%}
    </div>
{% endblock %}

cart/templates/cart/percentual_excedeu_limite.html
{% extends "materiais/base.html" %}
{% load static %}

{% block title %}
   O Percentual de Desconto excedeu o limite máximo!
{% endblock %}

{% block content %}
    <div class="d-block">
       <h3 align="center"><i class="fas fa-shopping-cart"></i> O Percentual de Desconto de {{ desconto}}% excedeu o limite máximo!</h3>

       <p class="text-right">
            <a href="{% url 'materiais:produto_list' %}" class="btn btn-outline-success" role="button">Continuar comprando</a>
       </p>
    </div>
{% endblock %}