accounts/urls.py
from collections import UserList

from django.conf.urls import url

from accounts import api_views
from accounts.views import UserprofileList, UserprofileDetalhe, UserprofileUpdate, userprofile_delete

app_name = 'accounts'

urlpatterns = [

    url(r'^userprofile-list/$', UserprofileList.as_view(), name='userprofile-list'),
    url(r'^userprofile-list/(?P<pk>[0-9]+)/$', UserprofileDetalhe.as_view(), name='userprofile-detail'),
    url(r'^userprofile/(?P<pk>[0-9]+)/edit/$', UserprofileUpdate.as_view(), name='userprofile-edit'),
    url(r'^userprofile/(?P<id>[0-9]+)/delete/$', userprofile_delete, name='userprofile-delete'),


]

cart/urls.py
from django.conf.urls import url
from . import views

app_name = 'cart'

urlpatterns = [
    url(r'^$', views.cart_detail, name='cart_detail'),
    url(r'^add/(?P<produto_id>\d+)/$', views.cart_add, name='cart_add'),
    url(r'^remove/(?P<produto_id>\d+)/$', views.cart_remove, name='cart_remove'),
]

faturamento/urls.py
from django.conf.urls import url

from faturamento import api_views
from faturamento.views import ParticipanteList, ParticipanteDetalhe, ParticipanteCreate, ParticipanteUpdate, \
    participante_delete

app_name = 'faturamento'

urlpatterns = [

    # Participante
    url(r'^participante_list/$', ParticipanteList.as_view(), name='participante_list'),
    url(r'^participante_list/(?P<pk>[0-9]+)/$', ParticipanteDetalhe.as_view(), name='participante_detail'),
    url(r'^participante_add/$', ParticipanteCreate.as_view(), name='participante_add'),
    url(r'^participante/(?P<pk>[0-9]+)/edit/$', ParticipanteUpdate.as_view(), name='participante_edit'),
    url(r'^participante/(?P<id>[0-9]+)/delete/$', participante_delete, name='participante_delete'),


]

materiais/urls.py
from django.conf.urls import url
from django.urls import path
from rest_framework.urlpatterns import format_suffix_patterns

from materiais import views
from materiais.views import PedidoWebTradicionalList, PedidoWebTradicionalDetalhe, \
    PedidoWebTradicionalUpdate, ProdutoDetalhe, ProdutoCreate, ProdutoList, manage_pedidowebitem

app_name = 'materiais'

urlpatterns = [
    
    # Pedido Tipo: Tradicional
    url(r'^pedidoweb_list/$', PedidoWebTradicionalList.as_view(), name='pedidoweb_list'),
    url(r'^pedidoweb_list/(?P<pk>[0-9]+)/$', PedidoWebTradicionalDetalhe.as_view(), name="pedidoweb_detail"),
    url(r'^pedidoweb_edit/(?P<pk>[0-9]+)/edit/$', PedidoWebTradicionalUpdate.as_view(), name='pedidoweb_edit'),
    
    url(r'^manage_pedidowebitem/(?P<pk>[0-9]+)/$', manage_pedidowebitem, name='manage_pedidowebitem'),

    
    url(r'^create/$', views.order_create, name='order_create'),
    # Pedido Tipo: E-Commerce
    # url(r'', views.ProdutoList.as_view(), name='produto_list'),
    url(r'^produto_list/$', ProdutoList.as_view(), name='produto_list'),
    url(r'^produto_list/(?P<categoria_slug>[-\w]+)/$', ProdutoList.as_view(), name='produto_list_by_category'),
    # url(r'^(?P<id>\d+)/(?P<slug>[-\w]+)/$', views.produto_detail, name='produto_detail'),
    url(r'^produto_list/(?P<id>\d+)/(?P<slug>[-\w]+)/$', views.produto_detail, name='produto_detail'),
    url(r'^produto_detalhe/(?P<pk>[0-9]+)/$', ProdutoDetalhe.as_view(), name="produto_detalhe"),
    url(r'^produto_add/$', ProdutoCreate.as_view(), name='produto_add'),

    # Index
    path('', views.ProdutoList.as_view(), name='home'),

    # Search PedidoWeb
    url(r'^search_pedidoweb/$', views.search_pedidoweb, name='search_pedidoweb'),


]

urlpatterns = format_suffix_patterns(urlpatterns)

usesoft_R3/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.contrib.auth.views import password_reset, password_reset_done, password_reset_confirm, \
    password_reset_complete
from django.urls import path, include
from rest_framework import routers
from rest_framework.schemas import get_schema_view

from accounts.views import login_view, logout_view
from django.conf.urls.static import static
from usesoft_R3 import settings

from materiais import api_views as materiais_api
from globais import api_views as globais_api
from financeiro import api_views as financeiro_api
from faturamento import api_views as faturamento_api
from accounts import api_views as accounts_api

from rest_framework.schemas import get_schema_view

schema_view = get_schema_view(title='Usesoft_R3 API',
                              url='https://central-aluminio.herokuapp.com/api/')

router = routers.DefaultRouter()
router.register(r'usuarios', accounts_api.UserViewSet)
router.register(r'grupos', accounts_api.GroupViewSet)
router.register(r'participantes', faturamento_api.ParticipanteViewSet)
router.register(r'gruposparticipantes', faturamento_api.GrupoParticipanteViewSet)
router.register(r'regioesdevenda', faturamento_api.RegiaoDeVendaViewSet)
router.register(r'tipospagamento', financeiro_api.TipoPagamentoViewSet)
router.register(r'prazospagamento', financeiro_api.PrazoPagamentoViewSet)
router.register(r'tiposdocumentos', financeiro_api.TipoDocumentoViewSet)
router.register(r'cfops', globais_api.CfopViewSet)
router.register(r'codigosncm', globais_api.CodigoNcmViewSet)
router.register(r'municipios', globais_api.MunicipioViewSet)
router.register(r'estados', globais_api.UfViewSet)
router.register(r'paises', globais_api.PaisIbgeViewSet)
router.register(r'mensagenspadrao', globais_api.MensagemPadraoViewSet)
router.register(r'tiposoperacoesfiscais', globais_api.TipoOperacaoFiscalViewSet)
router.register(r'pedidosweb', materiais_api.PedidoWebViewSet)
router.register(r'pedidowebitens', materiais_api.PedidoWebItemViewSet)
router.register(r'categorias', materiais_api.CategoriaViewSet)
router.register(r'produtos', materiais_api.ProdutoViewSet)

urlpatterns = [
    url(r'^schema/$', schema_view),
    url(r'^api/', include(router.urls)),
    url(r'^api-auth/', include('rest_framework.urls'),),
    path('admin/', admin.site.urls),
    url(r'^cart/', include('cart.urls')),
    url(r'^faturamento/', include('faturamento.urls')),
    url(r'^financeiro/', include('financeiro.urls')),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^', include('materiais.urls')),
    url(r'^login', login_view, name='login'),
    url(r'^logout', logout_view, name='logout'),
    # url(r'^change-password', change_password, name='change_password'),
    url(r'^reset-password/$', password_reset, name='reset_password'),
    url(r'^reset-password/done/$', password_reset_done, name='password_reset_done'),
    url(r'^reset-password/confirm/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        password_reset_confirm, name='password_reset_confirm'),
    url(r'^reset-password/complete/$', password_reset_complete, name='password_reset_complete'),



    ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

materiais/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin

from django.contrib.messages.views import SuccessMessageMixin
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

from django.db import transaction
from django.db.models import Q
from django.forms import inlineformset_factory
from django.http import HttpResponseRedirect

from django.shortcuts import render, get_object_or_404, redirect

from django.urls import reverse_lazy
from django.views.generic import CreateView, ListView, DetailView, UpdateView, DeleteView

from cart.cart import Cart
from cart.forms import CartAddProductForm
from faturamento.models import Participante

from materiais.filters import PedidoWebFilter
from materiais.forms import OrderCreateForm, PedidoWebFormSet
from materiais.models import Produto, PedidoWebItem, PedidoWeb


@login_required
def home(request):
    return render(request, 'materiais/produto/list.html')


"""
  TELA DE EMISSÃO DE PEDIDO TIPO E-COMMERCE
"""


class ProdutoCreate(SuccessMessageMixin, LoginRequiredMixin, CreateView):
    model = Produto
    fields = '__all__'
    template_name = 'materiais/produto/produto_form.html'


class ProdutoList(SuccessMessageMixin, LoginRequiredMixin, ListView):
    model = Produto
    context_object_name = 'produtos'
    template_name = 'materiais/produto/list.html'

    def get_queryset(self):
        valor = self.request.GET.get('q')
        if valor:
            object_list = self.model.objects.filter(
                Q(produto__icontains=valor) |
                Q(descricao__icontains=valor) |
                Q(preco_venda__icontains=valor) |
                Q(categoria__nome__icontains=valor)
            )
        else:
            object_list = self.model.objects.all()

        paginator = Paginator(object_list, 2)  # Show 2 produtos per page

        page = self.request.GET.get('page')
        try:
            queryset = paginator.page(page)
        except PageNotAnInteger:
            # If page is not an integer, deliver first page.
            queryset = paginator.page(1)
        except EmptyPage:
            # If page is out of range (e.g. 9999), deliver last page of results.
            queryset = paginator.page(paginator.num_pages)

        # return object_list
        return queryset


# @login_required
# def produto_list(request, categoria_slug=None):
#     categoria = None
#     categorias = Categoria.objects.all()
#     produtos = Produto.objects.filter(disponivel='S')
#     page = request.GET.get('page', 1)
#
#     paginator = Paginator(produtos, 10)
#     try:
#         produtos = paginator.page(page)
#     except PageNotAnInteger:
#         produtos = paginator.page(1)
#     except EmptyPage:
#         produtos = paginator.page(paginator.num_pages)
#
#     if categoria_slug:
#         categoria = get_object_or_404(Categoria, slug=categoria_slug)
#         produtos = produtos.filter(categoria=categoria)
#
#     return render(request, 'materiais/produto/list.html', {'categoria': categoria,
#                                                            'categorias': categorias,
#                                                            'produtos': produtos})


@login_required()
def produto_detail(request, id=None, slug=None):
    produto = get_object_or_404(Produto, id=id, slug=slug, disponivel='S')
    cart_produto_form = CartAddProductForm(initial={'preco_negociado': produto.preco_venda})
    return render(request, 'materiais/produto/detail.html', {'produto': produto,
                                                             'cart_produto_form': cart_produto_form})


class ProdutoDetalhe(SuccessMessageMixin, LoginRequiredMixin, DetailView):
    model = Produto
    context_object_name = 'produto'
    template_name = 'materiais/produto/produto_detail.html'


@login_required()
def order_create(request):
    cart = Cart(request)

    if request.method == 'POST':
        form = OrderCreateForm(request.POST, initial={'vendedor': request.user })

        if form.is_valid():
            pedidoweb = form.save(commit=False)

            # TODO Se o usuario for do Grupo Vendedor, já preenche o campo vendedor
            # TODO Caso contrário, Usuário precisa escolher o vendedor da lista

            if request.user.groups == "Clientes":
                pedidoweb.vendedor = request.user
                pedidoweb.participante = Participante.objects.get(vendedor=request.user)

            pedidoweb.total_produtos = cart.get_total_price()
            pedidoweb.save()

            seq = 0
            for item in cart:

                seq += 1
                PedidoWebItem.objects.create(pedidoweb=pedidoweb,
                                             sequencia=seq,
                                             produto=item['product'],
                                             unidade=item['unidade'],
                                             descricao=item['descricao'],
                                             observacoes=item['observacoes'],
                                             cfop=item['cfop'],
                                             codigo_ncm=item['codigo_ncm'],
                                             codigo_cest=item['codigo_cest'],
                                             status_pedido_item=item['status_pedido_item'],
                                             autorizacao_faturamento=item['autorizacao_faturamento'],
                                             autorizacao_numitem=item['autorizacao_numitem'],
                                             quantidade=item['quantity'],
                                             peso_liquido=item['peso_liquido'],
                                             peso_bruto=item['peso_bruto'],
                                             metro_cubico=item['metro_cubico'],
                                             movimenta_estoques=item['movimenta_estoques'],
                                             saldo_fisico=item['saldo_fisico'],
                                             saldo_fiscal=item['saldo_fiscal'],
                                             preco_custo=item['preco_custo'],
                                             preco_medio=item['preco_medio'],
                                             preco_custo_nfe=item['preco_custo_nfe'],
                                             preco_medio_nfe=item['preco_medio_nfe'],
                                             preco_unitario=item['price'],
                                             perc_desc=item['perc_desc'],
                                             custo_informado=item['custo_informado'],
                                             data_movimento=item['data_movimento'],
                                             participante=pedidoweb.participante,
                                             total_produto=item['total_produto'],
                                             modalidade_ipi=item['modalidade_ipi'],
                                             situacao_tributaria_ipi=item['situacao_tributaria_ipi'],
                                             base_calc_ipi=item['base_calc_ipi'],
                                             perc_ipi=item['perc_ipi'],
                                             perc_red_ipi=item['perc_red_ipi'],
                                             modalidade_calculo=item['modalidade_calculo'],
                                             modalidade_icms=item['modalidade_icms'],
                                             situacao_tributaria_icms=item['situacao_tributaria_icms'],
                                             base_calc_icms=item['base_calc_icms'],
                                             perc_icms=item['perc_icms'],
                                             perc_antec_tributaria=item['perc_antec_tributaria'],
                                             perc_red_icms=item['perc_red_icms'],
                                             modalidade_calculo_subst=item['modalidade_calculo_subst'],
                                             base_calc_icms_sub=item['base_calc_icms_sub'],
                                             perc_mva_sub=item['perc_mva_sub'],
                                             perc_icms_sub=item['perc_icms_sub'],
                                             base_calc_antecipacao_trib=item['base_calc_antecipacao_trib'],
                                             perc_antecipacao_trib=item['perc_antecipacao_trib'],
                                             situacao_tributaria_pis=item['situacao_tributaria_pis'],
                                             base_calc_pis=item['base_calc_pis'],
                                             perc_pis=item['perc_pis'],
                                             situacao_tributaria_cofins=item['situacao_tributaria_cofins'],
                                             base_calc_cofins=item['base_calc_cofins'],
                                             perc_fundo_pobreza=item['perc_fundo_pobreza'],
                                             perc_trib_aproximado=item['perc_trib_aproximado'],
                                             base_calc_import=item['base_calc_import'],
                                             perc_import=item['perc_import'],
                                             base_calc_issqn=item['base_calc_issqn'],
                                             perc_issqn=item['perc_issqn'],
                                             perc_desp_acessorias=item['perc_desp_acessorias'],
                                             perc_seguro=item['perc_seguro'],
                                             perc_frete=item['perc_frete'],
                                             natureza_custos=item['natureza_custos'],
                                             centro_custo=item['centro_custo'],

materiais/templates/materiais/base.html
{% load static %}
{% load l10n %}
{% load form_tags %}
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    <title>Usesoft Demo</title>

    <!-- Bootstrap CSS CDN -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css" integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4" crossorigin="anonymous">
    <!-- Our Custom CSS -->
    <link href="{% static 'css/base.css' %}" rel="stylesheet">
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
    <link href="{% static 'accounts/css/signin.css' %}" rel="stylesheet">

    <!-- Font Awesome JS -->
    <script defer src="https://use.fontawesome.com/releases/v5.0.13/js/solid.js" integrity="sha384-tzzSw1/Vo+0N5UhStP3bvwWPq+uvzCMfrN1fEFe+xBmv1C/AtVX5K0uZtmcHitFZ" crossorigin="anonymous"></script>
    <script defer src="https://use.fontawesome.com/releases/v5.0.13/js/fontawesome.js" integrity="sha384-6OIrr52G08NpOFSZdxxz1xdNSndlD4vdcf/q2myIUVO0VsqaGHJsB0RaBE01VTOY" crossorigin="anonymous"></script>


</head>

<body>

    <div class="wrapper">
        <!-- Sidebar  -->
        <nav id="sidebar">
            <div class="sidebar-header">
                <h3><a href="{% url 'materiais:home' %}">Usesoft Demo</a> </h3>
                <strong><a href="{% url 'materiais:home' %}">Use</a></strong>
            </div>

            <ul class="list-unstyled components">
                <li>
                    <a href="{% url 'materiais:pedidoweb_list' %}">
                        <i class="fas fa-home"></i>
                            Pedidos
                    </a>
                    {% if user.groups.all.0.name == "Vendedores" %}
                        <a href="{% url 'faturamento:participante_list' %}">
                            <i class="fas fa-briefcase"></i>
                            Clientes
                        </a>
                    {% endif %}
                    <a href="{% url 'materiais:produto_list' %}">
                        <i class="fas fa-copy"></i>
                        Produtos
                    </a>

                </li>


            </ul>

        </nav>

        <!-- Page Content  -->
        <div id="content">

            <nav class="navbar navbar-expand-lg navbar-light bg-light">
                <div class="container-fluid">

                    <button type="button" id="sidebarCollapse" class="btn btn-info">
                        <i class="fas fa-align-left"></i>
                        <span>Barra Lateral</span>
                    </button>
                    <button class="btn btn-dark d-inline-block d-lg-none ml-auto" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                        <i class="fas fa-align-justify"></i>
                    </button>

                    <div class="collapse navbar-collapse" id="navbarSupportedContent" align="right">
                        <ul class="nav navbar-nav ml-auto">
                            <li class="nav-item active">
                                <a class="nav-link" href="{% url 'materiais:home' %}">Guia Inicial</a>
                            </li>

                            <li class="nav-item dropdown">
                            {% if request.user.is_authenticated %}
                                <li class="nav-item dropdown">
                                    <a class="nav-link dropdown-toggle"  id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                      {{user.username}}
                                    </a>
                                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">

                                      <a class="dropdown-item" href="{% url 'reset_password' %}">Mudar a Senha</a>
                                      <a class="dropdown-item" href="{% url 'logout' %}">Sair</a>
                                    </div>
                                </li>

                                <li>
                                    <div>
                                        <div class="cart">
                                            {% with total_items=cart|length %}
                                                {% if cart|length > 0 %}
                                                    <a href="{% url 'cart:cart_detail' %}">
                                                        <i class="fas fa-shopping-cart fa-2x"></i>
                                                        <span class="badge badge-pill badge-warning">{{total_items}} item{{ total_items|localize|pluralize }}, R$ {{ cart.get_total_price|floatformat:2 }}</span>

                                                    </a>

                                                {% endif %}
                                            {% endwith %}
                                        </div>
                                    </div>
                                </li>

                            {% endif %}
                        </ul>
                    </div>
                </div>
            </nav>



            {% block content %}
            {% endblock %}

        </div>
    </div>

    <!-- jQuery CDN - Slim version (=without AJAX) -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
            integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
            crossorigin="anonymous"></script>

    <!-- Popper.JS -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js" integrity="sha384-cs/chFZiN24E4KMATLdqdvsezGxaGsi4hLGOzlXwp5UZB1LY//20VyM2taTB4QvJ" crossorigin="anonymous"></script>
    <!-- Bootstrap JS -->
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js" integrity="sha384-uefMccjFJAIv6A+rW+L4AHf99KvxDjWSu1z9VI8SKNVmz4sk7buKt/6v9KI65qnm" crossorigin="anonymous"></script>

    <script type="text/javascript">
        $(document).ready(function () {
            $('#sidebarCollapse').on('click', function () {
                $('#sidebar').toggleClass('active');
            });
        });
    </script>
</body>

</html>

materiais/templates/materiais/base_backup.html
{% load static %}
{% load l10n %}
<html>
    <head>
        <meta charset="utf-8" />
        <title>{% block title %}{% endblock %}</title>
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

        <!-- Bootstrap CSS -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
              integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
        <link href="{% static 'css/base.css' %}" rel="stylesheet">
        <link href="{% static 'accounts/css/signin.css' %}" rel="stylesheet">

        <!-- Use Font Awesome Free CDN -->
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/all.css" integrity="sha384-lKuwvrZot6UHsBSfcMvOkWwlCMgc0TaWr+30HWe3a4ltaBwTZhyTEggF5tJv8tbt" crossorigin="anonymous">
    </head>
<body>

    <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
      <div class="container">
        <a class="navbar-brand" href="/"><img src="{% static 'img/logo.jpg' %}" height="80" width="80"></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExample07"
                aria-controls="navbarsExample07" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        {% if request.user.is_authenticated %}
        <div class="collapse navbar-collapse" id="navbarsExample07">
              <ul class="navbar-nav mr-auto">
                    <li class="nav-item active">
                      <a class="nav-link" href="/">Início <span class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item">
                      <a class="nav-link" href="{% url 'faturamento:participante_list' %}">Participantes</a>
                    </li>
                    <li class="nav-item">
                        {% if request.user.is_superuser %}
                           <a class="nav-link" href="{% url 'materiais:pedidoweb_list' %}">Todos os Pedidos</a>
                        {% else %}
                           <a class="nav-link" href="{% url 'materiais:pedidoweb_list' %}">Meus Pedidos</a>
                        {% endif  %}
                    </li>
                    <li class="nav-item dropdown">
                         <a class="nav-link dropdown-toggle" href="http://example.com" id="dropdown07" data-toggle="dropdown"
                            aria-haspopup="true" aria-expanded="false">{{user.username}}
                         </a>
                         <div class="dropdown-menu" aria-labelledby="dropdown07">
                              <a class="dropdown-item" href="{% url 'accounts:userprofile-detail' request.user.id %}">Perfil</a>
                              <a class="dropdown-item" href="{% url 'reset_password' %}">Mudar a Senha</a>
                              <a class="dropdown-item" href="{% url 'logout' %}">Sair</a>
                         </div>
                    </li>
              </ul>
        </div>
        {% else %}
             <div class="dropdown-menu" aria-labelledby="dropdown07">
                      <a class="dropdown-item" href="#">Login</a>
             </div>
        {% endif %}
      </div>
    </nav>

    <div class="container">
        {% if request.user.is_authenticated %}
            <div class="container" id="subheader">

                <div class="cart">

                    {% with total_items=cart|length %}
                        {% if cart|length > 0 %}
                            Carrinho de Compras:
                            <a href="{% url 'cart:cart_detail' %}">
                                {{ total_items }} item{{ total_items|localize|pluralize }}, R$ {{ cart.get_total_price|floatformat:2 }}
                            </a>
                        {% endif %}
                    {% endwith %}
                </div>
            </div>
        {% endif %}
        <div class="d-block">
            {% block content %}
            {% endblock %}
        </div>
    </div>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->

    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
            integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
            crossorigin="anonymous">
    </script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
            integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
            crossorigin="anonymous">
    </script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
            integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
            crossorigin="anonymous">
    </script>


</body>
</html>

materiais/templates/materiais/confirm_delete.html
{% extends 'materiais/base.html' %}

{% block body %}
<div class="col-sm-6 col-sm-offset-3">
        <h1>Confirma Apagar</h1>
        <form method="POST" action="">{% csrf_token %}
            <p>Tem certeza que quer apagar: "{{ object }}" ?</p>
            <input type="submit" value="Confirma" class="btn btn-warning"/>
            <a href="{{ object.get_absolute_url }}" class="btn btn-primary">Voltar</a>
        </form>
</div>
{% endblock %}

materiais/templates/materiais/index.html
{% extends "materiais/base.html" %}
{% load static %}

{% block content %}

<main role="main">

      <div id="myCarousel" class="carousel slide" data-ride="carousel">
        <ol class="carousel-indicators">
          <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        </ol>
        <div class="carousel-inner">
          <div class="carousel-item active">
            <img class="first-slide" src="{% static 'img/aluminum-door.jpg' %}" alt="First slide">
            <div class="container">
              <div class="carousel-caption text-left">
                <h1>Pedido tipo E-Commerce</h1>
                <p>Pedido tipo E-Commerce</p>
                <p><a class="btn btn-lg btn-primary" href="{% url 'materiais:produto_list' %}" role="button">Pedido tipo E-Commerce</a></p>
              </div>
            </div>
          </div>

        </div>
        <a class="carousel-control-prev" href="#myCarousel" role="button" data-slide="prev">
          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
          <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#myCarousel" role="button" data-slide="next">
          <span class="carousel-control-next-icon" aria-hidden="true"></span>
          <span class="sr-only">Next</span>
        </a>
      </div>
</main>
{% endblock %}