cart/urls.py
from django.conf.urls import url
from . import views

app_name = 'cart'

urlpatterns = [
    url(r'^$', views.cart_detail, name='cart_detail'),
    url(r'^add/(?P<produto_id>\d+)/$', views.cart_add, name='cart_add'),
    url(r'^remove/(?P<produto_id>\d+)/$', views.cart_remove, name='cart_remove'),
]

materiais/urls.py
from django.conf.urls import url
from django.urls import path
from rest_framework.urlpatterns import format_suffix_patterns

from materiais import views
from materiais.views import PedidoWebTradicionalList, PedidoWebTradicionalDetalhe, \
    PedidoWebTradicionalUpdate, ProdutoDetalhe, ProdutoCreate, ProdutoList, manage_pedidowebitem

app_name = 'materiais'

urlpatterns = [
    
    # Pedido Tipo: Tradicional
    url(r'^pedidoweb_list/$', PedidoWebTradicionalList.as_view(), name='pedidoweb_list'),
    url(r'^pedidoweb_list/(?P<pk>[0-9]+)/$', PedidoWebTradicionalDetalhe.as_view(), name="pedidoweb_detail"),
    url(r'^pedidoweb_edit/(?P<pk>[0-9]+)/edit/$', PedidoWebTradicionalUpdate.as_view(), name='pedidoweb_edit'),
    
    url(r'^manage_pedidowebitem/(?P<pk>[0-9]+)/$', manage_pedidowebitem, name='manage_pedidowebitem'),

    
    url(r'^create/$', views.order_create, name='order_create'),
    # Pedido Tipo: E-Commerce
    # url(r'', views.ProdutoList.as_view(), name='produto_list'),
    url(r'^produto_list/$', ProdutoList.as_view(), name='produto_list'),
    url(r'^produto_list/(?P<categoria_slug>[-\w]+)/$', ProdutoList.as_view(), name='produto_list_by_category'),
    # url(r'^(?P<id>\d+)/(?P<slug>[-\w]+)/$', views.produto_detail, name='produto_detail'),
    url(r'^produto_list/(?P<id>\d+)/(?P<slug>[-\w]+)/$', views.produto_detail, name='produto_detail'),
    url(r'^produto_detalhe/(?P<pk>[0-9]+)/$', ProdutoDetalhe.as_view(), name="produto_detalhe"),
    url(r'^produto_add/$', ProdutoCreate.as_view(), name='produto_add'),

    # Index
    path('', views.ProdutoList.as_view(), name='home'),

    # Search PedidoWeb
    url(r'^search_pedidoweb/$', views.search_pedidoweb, name='search_pedidoweb'),


]

urlpatterns = format_suffix_patterns(urlpatterns)

usesoft_R3/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.contrib.auth.views import password_reset, password_reset_done, password_reset_confirm, \
    password_reset_complete
from django.urls import path, include
from rest_framework import routers
from rest_framework.schemas import get_schema_view

from accounts.views import login_view, logout_view
from django.conf.urls.static import static
from usesoft_R3 import settings

from materiais import api_views as materiais_api
from globais import api_views as globais_api
from financeiro import api_views as financeiro_api
from faturamento import api_views as faturamento_api
from accounts import api_views as accounts_api

from rest_framework.schemas import get_schema_view

schema_view = get_schema_view(title='Usesoft_R3 API',
                              url='https://central-aluminio.herokuapp.com/api/')

router = routers.DefaultRouter()
router.register(r'usuarios', accounts_api.UserViewSet)
router.register(r'grupos', accounts_api.GroupViewSet)
router.register(r'participantes', faturamento_api.ParticipanteViewSet)
router.register(r'gruposparticipantes', faturamento_api.GrupoParticipanteViewSet)
router.register(r'regioesdevenda', faturamento_api.RegiaoDeVendaViewSet)
router.register(r'tipospagamento', financeiro_api.TipoPagamentoViewSet)
router.register(r'prazospagamento', financeiro_api.PrazoPagamentoViewSet)
router.register(r'tiposdocumentos', financeiro_api.TipoDocumentoViewSet)
router.register(r'cfops', globais_api.CfopViewSet)
router.register(r'codigosncm', globais_api.CodigoNcmViewSet)
router.register(r'municipios', globais_api.MunicipioViewSet)
router.register(r'estados', globais_api.UfViewSet)
router.register(r'paises', globais_api.PaisIbgeViewSet)
router.register(r'mensagenspadrao', globais_api.MensagemPadraoViewSet)
router.register(r'tiposoperacoesfiscais', globais_api.TipoOperacaoFiscalViewSet)
router.register(r'pedidosweb', materiais_api.PedidoWebViewSet)
router.register(r'pedidowebitens', materiais_api.PedidoWebItemViewSet)
router.register(r'categorias', materiais_api.CategoriaViewSet)
router.register(r'produtos', materiais_api.ProdutoViewSet)

urlpatterns = [
    url(r'^schema/$', schema_view),
    url(r'^api/', include(router.urls)),
    url(r'^api-auth/', include('rest_framework.urls'),),
    path('admin/', admin.site.urls),
    url(r'^cart/', include('cart.urls')),
    url(r'^faturamento/', include('faturamento.urls')),
    url(r'^financeiro/', include('financeiro.urls')),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^', include('materiais.urls')),
    url(r'^login', login_view, name='login'),
    url(r'^logout', logout_view, name='logout'),
    # url(r'^change-password', change_password, name='change_password'),
    url(r'^reset-password/$', password_reset, name='reset_password'),
    url(r'^reset-password/done/$', password_reset_done, name='password_reset_done'),
    url(r'^reset-password/confirm/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        password_reset_confirm, name='password_reset_confirm'),
    url(r'^reset-password/complete/$', password_reset_complete, name='password_reset_complete'),



    ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

materiais/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin

from django.contrib.messages.views import SuccessMessageMixin
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

from django.db import transaction
from django.db.models import Q
from django.forms import inlineformset_factory
from django.http import HttpResponseRedirect

from django.shortcuts import render, get_object_or_404, redirect

from django.urls import reverse_lazy
from django.views.generic import CreateView, ListView, DetailView, UpdateView, DeleteView

from cart.cart import Cart
from cart.forms import CartAddProductForm
from faturamento.models import Participante

from materiais.filters import PedidoWebFilter
from materiais.forms import OrderCreateForm, PedidoWebFormSet
from materiais.models import Produto, PedidoWebItem, PedidoWeb


@login_required
def home(request):
    return render(request, 'materiais/produto/list.html')


"""
  TELA DE EMISSÃO DE PEDIDO TIPO E-COMMERCE
"""


class ProdutoCreate(SuccessMessageMixin, LoginRequiredMixin, CreateView):
    model = Produto
    fields = '__all__'
    template_name = 'materiais/produto/produto_form.html'


class ProdutoList(SuccessMessageMixin, LoginRequiredMixin, ListView):
    model = Produto
    context_object_name = 'produtos'
    template_name = 'materiais/produto/list.html'

    def get_queryset(self):
        valor = self.request.GET.get('q')
        if valor:
            object_list = self.model.objects.filter(
                Q(produto__icontains=valor) |
                Q(descricao__icontains=valor) |
                Q(preco_venda__icontains=valor) |
                Q(categoria__nome__icontains=valor)
            )
        else:
            object_list = self.model.objects.all()

        paginator = Paginator(object_list, 2)  # Show 2 produtos per page

        page = self.request.GET.get('page')
        try:
            queryset = paginator.page(page)
        except PageNotAnInteger:
            # If page is not an integer, deliver first page.
            queryset = paginator.page(1)
        except EmptyPage:
            # If page is out of range (e.g. 9999), deliver last page of results.
            queryset = paginator.page(paginator.num_pages)

        # return object_list
        return queryset


# @login_required
# def produto_list(request, categoria_slug=None):
#     categoria = None
#     categorias = Categoria.objects.all()
#     produtos = Produto.objects.filter(disponivel='S')
#     page = request.GET.get('page', 1)
#
#     paginator = Paginator(produtos, 10)
#     try:
#         produtos = paginator.page(page)
#     except PageNotAnInteger:
#         produtos = paginator.page(1)
#     except EmptyPage:
#         produtos = paginator.page(paginator.num_pages)
#
#     if categoria_slug:
#         categoria = get_object_or_404(Categoria, slug=categoria_slug)
#         produtos = produtos.filter(categoria=categoria)
#
#     return render(request, 'materiais/produto/list.html', {'categoria': categoria,
#                                                            'categorias': categorias,
#                                                            'produtos': produtos})


@login_required()
def produto_detail(request, id=None, slug=None):
    produto = get_object_or_404(Produto, id=id, slug=slug, disponivel='S')
    cart_produto_form = CartAddProductForm(initial={'preco_negociado': produto.preco_venda})
    return render(request, 'materiais/produto/detail.html', {'produto': produto,
                                                             'cart_produto_form': cart_produto_form})


class ProdutoDetalhe(SuccessMessageMixin, LoginRequiredMixin, DetailView):
    model = Produto
    context_object_name = 'produto'
    template_name = 'materiais/produto/produto_detail.html'


@login_required()
def order_create(request):
    cart = Cart(request)

    if request.method == 'POST':
        form = OrderCreateForm(request.POST, initial={'vendedor': request.user })

        if form.is_valid():
            pedidoweb = form.save(commit=False)

            # TODO Se o usuario for do Grupo Vendedor, já preenche o campo vendedor
            # TODO Caso contrário, Usuário precisa escolher o vendedor da lista

            if request.user.groups == "Clientes":
                pedidoweb.vendedor = request.user
                pedidoweb.participante = Participante.objects.get(vendedor=request.user)

            pedidoweb.total_produtos = cart.get_total_price()
            pedidoweb.save()

            seq = 0
            for item in cart:

                seq += 1
                PedidoWebItem.objects.create(pedidoweb=pedidoweb,
                                             sequencia=seq,
                                             produto=item['product'],
                                             unidade=item['unidade'],
                                             descricao=item['descricao'],
                                             observacoes=item['observacoes'],
                                             cfop=item['cfop'],
                                             codigo_ncm=item['codigo_ncm'],
                                             codigo_cest=item['codigo_cest'],
                                             status_pedido_item=item['status_pedido_item'],
                                             autorizacao_faturamento=item['autorizacao_faturamento'],
                                             autorizacao_numitem=item['autorizacao_numitem'],
                                             quantidade=item['quantity'],
                                             peso_liquido=item['peso_liquido'],
                                             peso_bruto=item['peso_bruto'],
                                             metro_cubico=item['metro_cubico'],
                                             movimenta_estoques=item['movimenta_estoques'],
                                             saldo_fisico=item['saldo_fisico'],
                                             saldo_fiscal=item['saldo_fiscal'],
                                             preco_custo=item['preco_custo'],
                                             preco_medio=item['preco_medio'],
                                             preco_custo_nfe=item['preco_custo_nfe'],
                                             preco_medio_nfe=item['preco_medio_nfe'],
                                             preco_unitario=item['price'],
                                             perc_desc=item['perc_desc'],
                                             custo_informado=item['custo_informado'],
                                             data_movimento=item['data_movimento'],
                                             participante=pedidoweb.participante,
                                             total_produto=item['total_produto'],
                                             modalidade_ipi=item['modalidade_ipi'],
                                             situacao_tributaria_ipi=item['situacao_tributaria_ipi'],
                                             base_calc_ipi=item['base_calc_ipi'],
                                             perc_ipi=item['perc_ipi'],
                                             perc_red_ipi=item['perc_red_ipi'],
                                             modalidade_calculo=item['modalidade_calculo'],
                                             modalidade_icms=item['modalidade_icms'],
                                             situacao_tributaria_icms=item['situacao_tributaria_icms'],
                                             base_calc_icms=item['base_calc_icms'],
                                             perc_icms=item['perc_icms'],
                                             perc_antec_tributaria=item['perc_antec_tributaria'],
                                             perc_red_icms=item['perc_red_icms'],
                                             modalidade_calculo_subst=item['modalidade_calculo_subst'],
                                             base_calc_icms_sub=item['base_calc_icms_sub'],
                                             perc_mva_sub=item['perc_mva_sub'],
                                             perc_icms_sub=item['perc_icms_sub'],
                                             base_calc_antecipacao_trib=item['base_calc_antecipacao_trib'],
                                             perc_antecipacao_trib=item['perc_antecipacao_trib'],
                                             situacao_tributaria_pis=item['situacao_tributaria_pis'],
                                             base_calc_pis=item['base_calc_pis'],
                                             perc_pis=item['perc_pis'],
                                             situacao_tributaria_cofins=item['situacao_tributaria_cofins'],
                                             base_calc_cofins=item['base_calc_cofins'],
                                             perc_fundo_pobreza=item['perc_fundo_pobreza'],
                                             perc_trib_aproximado=item['perc_trib_aproximado'],
                                             base_calc_import=item['base_calc_import'],
                                             perc_import=item['perc_import'],
                                             base_calc_issqn=item['base_calc_issqn'],
                                             perc_issqn=item['perc_issqn'],
                                             perc_desp_acessorias=item['perc_desp_acessorias'],
                                             perc_seguro=item['perc_seguro'],
                                             perc_frete=item['perc_frete'],
                                             natureza_custos=item['natureza_custos'],
                                             centro_custo=item['centro_custo'],

materiais/templates/materiais/produto/detail.html
{% extends "materiais/base.html" %}
{% load static %}

{% block title %}
    {{ produto.descricao }}
{% endblock %}


{% block content %}
    {% if messages %}
        <ul class="messages">
            {% for message in messages %}
            <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}
    <div class="product-detail">
       <!-- <img src="{% if produto.image %}{{ produto.image.url }}{% else %}{% static 'img/no_image.png' %}{% endif %}">-->

        <h4>Código: {{ produto.produto }} - {{ produto.descricao }}</h4>
        <h6><a href="{{ produto.categoria.get_absolute_url }}">Categoria: {{ produto.categoria }}</a></h6>
        <p class="price"><h6>Preço Unitário: R$ {{ produto.preco_venda }}</h6></p>
        <form action="{% url 'cart:cart_add' produto.id %}" method="post">
            {{ cart_produto_form }}
            {% csrf_token %}

            <input type="submit" value="Adicionar ao Carrinho">
            <i class="fas fa-thumbs-up fa-2x"></i>

        </form>

    </div>
{% endblock %}

materiais/templates/materiais/produto/list.html
{% extends "materiais/base.html" %}


{% block title %}
    {% if category %}{{ categoria.nome }}{% else %}Produtos{% endif %}
{% endblock %}

{% block content %}


<!--<div id="main" class="d-block product-list">-->
{% if messages %}
    <ul class="messages">
        {% for message in messages %}
        <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
        {% endfor %}
    </ul>
{% endif %}

<div class="container">
    {% if produtos %}
    <div class="card-group">

        <div class="card bg-light" align="center">
            <div class="card-body">
                <h5 style="margin-center"><strong>Lista de Produtos</strong></h5>
            </div>
        </div>

        <div class="card bg-light" align="center">
            <div class="card-body">
             <!-- Pesquisa -->
            <form class="form-inline mt-2 mt-md-0">
                <input class="form-control mr-sm-2" id="searchbox" name="q" type="text" value="{{ request.GET.q }}" placeholder="código, descrição ou preço..." aria-label="Search">
                <button class="btn btn-outline-success my-2 my-sm-0" data-toggle="tooltip" data-placement="top" title="Pesquisar" type="submit"><i class="fas fa-search"></i></button>
            </form>
            </div>
        </div>

        <div class="card bg-light" align="center">
            <div class="card-body">
            <!-- pagination -->
            <nav aria-label="Page navigation example">
              <ul class="pagination pagination-sm justify-content-end">

                {% if object_list.has_previous %}
                <li class="page-item"><a class="page-link" href="?page={{ object_list.previous_page_number }}&q={{ request.GET.q }}"><i class="fas fa-chevron-circle-left"></i> Anterior</a></li>
                {% endif %}

                <li class="page-item active">
                    <span class="page-link">
                            Página {{ object_list.number }} de {{ object_list.paginator.num_pages }}
                            <span class="sr-only">(current)</span>
                    </span>
                </li>

                {% if object_list.has_next %}
                <li class="page-item"><a class="page-link" href="?page={{ object_list.next_page_number }}&q={{ request.GET.q }}"><i class="fas fa-chevron-circle-right"></i> Próxima</a></li>
                {% endif %}

              </ul>
            </nav>
            <!--end of pagination-->
            </div>
        </div>

    </div>
    <!--end of card-group-->
</div>

<div class="container">
        <div class="row">
            {% for produto in produtos %}
                <div class="col-sm-12">
                    <div class="card border-dark mb-3" style="background-color: #eee;">
                        <div class="card-body">
                            <h5 class="card-title">{% for item in cart %} {% if item.product == produto %} <span class="badge badge-pill badge-warning"><i class="fas fa-check-square"></i> adicionado</span>  {% endif %} {% endfor %}</h5>
                            <h5 class="card-subtitle mb-2 ">{{ produto.produto }} - {{ produto.descricao }}</h5>
                            <p class="card-text">{{ produto.preco_venda }}</p>
                            <a href="{{ produto.get_absolute_url }}" class="btn btn-outline-warning btn-sm"><i class="fas fa-check-square"></i> Vender</a>
                            <a href="{% url 'materiais:produto_detalhe' produto.id %}" class="btn btn-outline-primary btn-sm"><i class="fas fa-info-circle"></i> Detalhes</a>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>

    {% else %}
        <h2>Nenhum registro encontrado para a pesquisa {{ request.GET.q }} </h2>
        <div align="right">
            <a class="nav-link" href="{% url 'materiais:produto_list' %}">
                <i class="fas fa-arrow-circle-left"></i> Voltar
            </a>
        </div>
    {% endif %}

</div>

{% endblock %}

materiais/templates/materiais/produto/list_backup.html
{% extends "materiais/base.html" %}
{% load static %}

{% block title %}
    {% if category %}{{ categoria.nome }}{% else %}Produtos{% endif %}
{% endblock %}

{% block content %}

{% if messages %}
    <ul class="messages">
        {% for message in messages %}
        <li>{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
        {% endfor %}
    </ul>
{% endif %}


<!--<div id="main" class="d-block product-list">-->
<div class="container">
    {% if produtos %}
    <div class="card-group">

        <div class="card" align="center">
            <h5 style="margin-center"><strong>Lista de Produtos</strong></h5>
        </div>

        <div class="card" align="center">
             <!-- Pesquisa -->
            <form class="form-inline mt-2 mt-md-0">
                <input class="form-control mr-sm-2" id="searchbox" name="q" type="text" value="{{ request.GET.q }}" placeholder="código, descrição ou preço..." aria-label="Search">
                <button class="btn btn-outline-success my-2 my-sm-0" type="submit"> <i class="fas fa-search"></i> Pesquisa</button>
            </form>
        </div>

        <div class="card" align="center">
            <!-- pagination -->
            <nav aria-label="Page navigation example">
              <ul class="pagination pagination-sm justify-content-end">

                {% if object_list.has_previous %}
                <li class="page-item"><a class="page-link" href="?page={{ object_list.previous_page_number }}&q={{ request.GET.q }}"><i class="fas fa-chevron-circle-left"></i> Anterior</a></li>
                {% endif %}

                <li class="page-item active">
                    <span class="page-link">
                            Página {{ object_list.number }} de {{ object_list.paginator.num_pages }}
                            <span class="sr-only">(current)</span>
                    </span>
                </li>

                {% if object_list.has_next %}
                <li class="page-item"><a class="page-link" href="?page={{ object_list.next_page_number }}&q={{ request.GET.q }}"><i class="fas fa-chevron-circle-right"></i> Próxima</a></li>
                {% endif %}

              </ul>
            </nav>
            <!--end of pagination-->
        </div>

    </div>
    <!--end of card-group-->


    <table class="table table-responsive table-condensed table-bordered table-hover table-striped">
        <tbody>
            <tr>
                <th>Categoria</th>
                <th>Código</th>
                <th>Descrição</th>
                <th>Preço</th>
                <th>Ações</th>
            </tr>
            <tfoot>
                <tr>
                    <th>Categoria</th>
                    <th>Código</th>
                    <th>Descrição</th>
                    <th>Preço</th>
                    <th>Ações</th>
                </tr>
            </tfoot>
            {% for produto in produtos %}

                <div class="row">

                    <tr>

                       <td>{{ produto.categoria }}</td>
                       <td>{{ produto.produto }}</td>
                       <td>{{ produto.descricao }}</td>
                       <td>{{ produto.preco_venda }}</td>
                       <td>
                        <a href="{{ produto.get_absolute_url }}" class="btn btn-outline-primary btn-sm"><i class="fas fa-check-square"></i> Comprar</a>
                       </td>

                    </tr>

                </div>

            {% endfor %}
        </tbody>
        
    </table>
    {% else %}
        <h2>Nenhum registro encontrado para a pesquisa {{ request.GET.q }} </h2>
        <div align="right">
            <a class="nav-link" href="{% url 'materiais:produto_list' %}">
                <i class="fas fa-arrow-circle-left"></i> Voltar
            </a>
        </div>
    {% endif %}

</div>

{% endblock %}

materiais/templates/materiais/produto/produto_detail.html
{% extends "materiais/base.html" %}
{% load static %}
{% load l10n %}

{% block title %}Detalhes do Produto{% endblock %}


{% block content %}

{% if messages %}
    <ul class="messages">
        {% for message in messages %}
        <li>{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
        {% endfor %}
    </ul>
{% endif %}


    <div align="right">
        <a class="nav-link" href="{% url 'materiais:produto_list' %}">
            <i class="fas fa-arrow-circle-left"></i> Voltar
        </a>
    </div>

    <ul>
        <li><h4>Produto: {{ produto.produto }} - {{ produto.descricao}}</h4></li>
        <li><h4>Preço: {{ produto.preco_venda}} </h4></li>


    </ul>



{% endblock %}

materiais/templates/materiais/produto/produto_form.html
{% extends 'materiais/base.html' %}
{% load l10n %}

{% block content %}

{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li>{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}

<div class="col-md-offset-2"> <!-- Header -->
    <!-- Left Contato Info -->
    <div class="panel panel-default">
        <div class="panel-body">
            {% if pedidoweb.id %}
            <h4>Edita o Produto {{pedidoweb.id}}</h4>
            {% else %}
            <h4>Cria um Novo Produto</h4>
            {% endif %}

            <div align="right">
                <a class="nav-link" href="{% url 'materiais:produto_list' %}">
                     <i class="fas fa-arrow-circle-left"></i> Voltar
                </a>
            </div>
        </div>
    </div>


    <form action="" method="post">{% csrf_token %}

        <div class="container">
            {{ form.as_p }}
        </div>

        <div align="right">
            <input type="submit" value="Gravar"/>
        </div>
    </form>
</div>


{% endblock %}