cart/urls.py
from django.conf.urls import url
from . import views

app_name = 'cart'

urlpatterns = [
    url(r'^$', views.cart_detail, name='cart_detail'),
    url(r'^add/(?P<produto_id>\d+)/$', views.cart_add, name='cart_add'),
    url(r'^remove/(?P<produto_id>\d+)/$', views.cart_remove, name='cart_remove'),
]

faturamento/urls.py
from django.conf.urls import url

from faturamento import api_views
from faturamento.views import ParticipanteList, ParticipanteDetalhe, ParticipanteCreate, ParticipanteUpdate, \
    participante_delete

app_name = 'faturamento'

urlpatterns = [

    # Participante
    url(r'^participante_list/$', ParticipanteList.as_view(), name='participante_list'),
    url(r'^participante_list/(?P<pk>[0-9]+)/$', ParticipanteDetalhe.as_view(), name='participante_detail'),
    url(r'^participante_add/$', ParticipanteCreate.as_view(), name='participante_add'),
    url(r'^participante/(?P<pk>[0-9]+)/edit/$', ParticipanteUpdate.as_view(), name='participante_edit'),
    url(r'^participante/(?P<id>[0-9]+)/delete/$', participante_delete, name='participante_delete'),


]

usesoft_R3/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.contrib.auth.views import password_reset, password_reset_done, password_reset_confirm, \
    password_reset_complete
from django.urls import path, include
from rest_framework import routers
from rest_framework.schemas import get_schema_view

from accounts.views import login_view, logout_view
from django.conf.urls.static import static
from usesoft_R3 import settings

from materiais import api_views as materiais_api
from globais import api_views as globais_api
from financeiro import api_views as financeiro_api
from faturamento import api_views as faturamento_api
from accounts import api_views as accounts_api

from rest_framework.schemas import get_schema_view

schema_view = get_schema_view(title='Usesoft_R3 API',
                              url='https://central-aluminio.herokuapp.com/api/')

router = routers.DefaultRouter()
router.register(r'usuarios', accounts_api.UserViewSet)
router.register(r'grupos', accounts_api.GroupViewSet)
router.register(r'participantes', faturamento_api.ParticipanteViewSet)
router.register(r'gruposparticipantes', faturamento_api.GrupoParticipanteViewSet)
router.register(r'regioesdevenda', faturamento_api.RegiaoDeVendaViewSet)
router.register(r'tipospagamento', financeiro_api.TipoPagamentoViewSet)
router.register(r'prazospagamento', financeiro_api.PrazoPagamentoViewSet)
router.register(r'tiposdocumentos', financeiro_api.TipoDocumentoViewSet)
router.register(r'cfops', globais_api.CfopViewSet)
router.register(r'codigosncm', globais_api.CodigoNcmViewSet)
router.register(r'municipios', globais_api.MunicipioViewSet)
router.register(r'estados', globais_api.UfViewSet)
router.register(r'paises', globais_api.PaisIbgeViewSet)
router.register(r'mensagenspadrao', globais_api.MensagemPadraoViewSet)
router.register(r'tiposoperacoesfiscais', globais_api.TipoOperacaoFiscalViewSet)
router.register(r'pedidosweb', materiais_api.PedidoWebViewSet)
router.register(r'pedidowebitens', materiais_api.PedidoWebItemViewSet)
router.register(r'categorias', materiais_api.CategoriaViewSet)
router.register(r'produtos', materiais_api.ProdutoViewSet)

urlpatterns = [
    url(r'^schema/$', schema_view),
    url(r'^api/', include(router.urls)),
    url(r'^api-auth/', include('rest_framework.urls'),),
    path('admin/', admin.site.urls),
    url(r'^cart/', include('cart.urls')),
    url(r'^faturamento/', include('faturamento.urls')),
    url(r'^financeiro/', include('financeiro.urls')),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^', include('materiais.urls')),
    url(r'^login', login_view, name='login'),
    url(r'^logout', logout_view, name='logout'),
    # url(r'^change-password', change_password, name='change_password'),
    url(r'^reset-password/$', password_reset, name='reset_password'),
    url(r'^reset-password/done/$', password_reset_done, name='password_reset_done'),
    url(r'^reset-password/confirm/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        password_reset_confirm, name='password_reset_confirm'),
    url(r'^reset-password/complete/$', password_reset_complete, name='password_reset_complete'),



    ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

faturamento/models.py
from django.contrib.auth.models import User
from django.core.validators import MaxValueValidator
from django.db import models
from django.urls import reverse

from choices.models import SIM_NAO_CHOICES, FISICA_JURIDICA_CHOICES
from globais.models import Uf, Municipio, PaisIbge


# ---------------------------------------------------------------------------------------------------------------------
# grupos de clientes
# ---------------------------------------------------------------------------------------------------------------------
class GrupoParticipante(models.Model):
    codigo = models.CharField("Código do Grupo de participantes", unique=True, max_length=5)
    descricao = models.CharField("Descrição do Grupo de participantes", max_length=80)

    habilitado = models.CharField("Habilitado para uso", max_length=1, default="S",
                                  choices=SIM_NAO_CHOICES,
                                  help_text='Desabilite este Grupo caso sua empresa não o utilize ou utilize muito '
                                            'esporadicamente para evitar erros')
    ultima_alteracao = models.DateTimeField(null=True, blank=True)

    def __str__(self):
        return self.codigo + " - " + self.descricao

    class Meta:
        ordering = ('descricao',)
        verbose_name = "Grupo de Participante"
        verbose_name_plural = "Grupos de Participantes"


# -----------------------------------------------------------------------------------------------------------------------
# regiões de vendas
# -----------------------------------------------------------------------------------------------------------------------
class RegiaoDeVenda(models.Model):
    codigo = models.CharField("Código da região de vendas", unique=True, max_length=5, null=False)
    descricao = models.CharField("Descrição da região de vendas", max_length=80, null=False)
    habilitado = models.CharField("Habilitado para uso", max_length=1, null=False, default="N",
                                  choices=SIM_NAO_CHOICES,
                                  help_text='Desabilite este CFOP caso sua empresa não o utilize ou utilize muito '
                                            'esporadicamente para evitar erros')
    ultima_alteracao = models.DateTimeField(null=True, blank=True)

    def __str__(self):
        return self.codigo + " - "+self.descricao

    class Meta:
        ordering = ('descricao',)
        verbose_name = "Região de Venda"
        verbose_name_plural = "Regiões de Vendas"


# ----------------------------------------------------------------------------------------------------------------------
# códigos de participantes clientes ou fornecedores (kfai01)
# ----------------------------------------------------------------------------------------------------------------------
class Participante(models.Model):
    razao_social = models.CharField(max_length=50, blank=False)
    nome_fantasia = models.CharField("Nome Fantasia", max_length=50, blank=False)
    fisica_juridica = models.CharField("Pessoa Física(F) ou Jurídica (J)", max_length=1, blank=False,
                                       choices=FISICA_JURIDICA_CHOICES, default='J')
    cnpj_cpf = models.CharField("CNPJ/CPF", max_length=14, blank=True, null=True)
    inscricao_estadual = models.CharField("Inscricao Estadual", max_length=15, blank=False,
                                          default="ISENTO")
    inscricao_municipal = models.CharField("Inscrição Municipal", max_length=15,
                                           blank=True, default="ISENTO")

    # TODO Depois excluir a opção null=True
    codigo = models.PositiveIntegerField("Código", validators=[MaxValueValidator(99999999)], blank=True, null=True)

    vendedor = models.ForeignKey(User, on_delete=models.DO_NOTHING, blank=True, null=True, related_name="responsavel")

    # TODO 1. Depois excluir a opção null=True
    regiao_de_venda = models.ForeignKey(RegiaoDeVenda, on_delete=models.CASCADE, blank=True, null=True)
    # regiao_de_venda = models.IntegerField(blank=True, null=True)

    # TODO 2. Depois excluir a opção null=True
    grupo = models.ForeignKey(GrupoParticipante, on_delete=models.CASCADE, blank=True, null=True)

    endereco = models.CharField("Endereço", max_length=60, blank=True, null=True)
    complemento = models.CharField("Complemento", max_length=60, blank=True, null=True)
    numero = models.CharField("Número", max_length=10, blank=True, null=True)
    bairro = models.CharField("Bairro", max_length=10, blank=True, null=True)

    # TODO 3. Depois excluir a opção null=True
    cidade = models.ForeignKey(Municipio, on_delete=models.CASCADE, blank=True, null=True)
    # cidade = models.IntegerField(blank=True, null=True)

    cep = models.PositiveIntegerField("CEP", null=True, blank=True,
                                      validators=[MaxValueValidator(99999999)])

    # TODO 4. Depois excluir a opção null=True
    estado = models.ForeignKey(Uf, on_delete=models.CASCADE, blank=True, null=True)
    # estado = models.IntegerField(blank=True, null=True)

    # TODO 5. Depois excluir a opção null=True
    pais = models.ForeignKey(PaisIbge, on_delete=models.CASCADE, blank=True, null=True)
    # pais = models.IntegerField(blank=True, null=True)

    telefone = models.CharField("Telefone 1", max_length=20, blank=True, null=True)

    telefone2 = models.CharField("Telefone 2", max_length=20, blank=True, null=True)

    celular = models.CharField("Celular 1", max_length=20, blank=True, null=True)

    celular2 = models.CharField("Celular 2", max_length=20, blank=True, null=True)

    email = models.CharField("E-mail", max_length=40, blank=True, null=True)
    
    ultima_alteracao = models.DateTimeField(null=True, blank=True)

    def get_absolute_url(self):
        return reverse('faturamento:participante_detail', kwargs={'pk': self.pk})

    def __str__(self):
        return str(self.razao_social)

    def exibe_complemento(self):
        if self.complemento:
            return self.complemento
        else:
            return "-"

    def exibe_bairro(self):
        if self.bairro:
            return self.bairro
        else:
            return "-"

    def exibe_telefone2(self):
        if self.telefone2:
            return self.telefone2
        else:
            return "-"

    def exibe_email(self):
        if self.email:
            return self.email
        else:
            return "Favor atualizar E-mail."

    def exibe_fisica_juridica(self):
        if self.fisica_juridica == 'J':
            return "Pessoa Jurídica"
        else:
            return "Pessoa Física"

    class Meta:
        ordering = ['razao_social']
        verbose_name = 'Cadastro de Participante'
        verbose_name_plural = 'Cadastro de Participantes'


# ---------------------------------------------------------------------------------------------------------------------
#  dados da nota fiscal
# ---------------------------------------------------------------------------------------------------------------------
class NotaFiscal(models.Model):
    numero_nfe = models.PositiveIntegerField("Número da Nota Fiscal", null=True, blank=True,
                                             validators=[MaxValueValidator(99999999)])
    serie_nfe = models.PositiveIntegerField("Série da Nota Fiscal", null=True, blank=True,
                                            validators=[MaxValueValidator(999)])
    subserie_nfe = models.PositiveIntegerField("SubSérie da Nota fiscal", null=True, blank=True,
                                               validators=[MaxValueValidator(999)])
    ultima_alteracao = models.DateTimeField(null=True, blank=True)

    def __str__(self):
        return str(self.numero_nfe)

    class Meta:
        ordering = ['numero_nfe']
        verbose_name = 'Cadastro de notas fiscais emitidas e recebidas'
        verbose_name_plural = 'Cadastro de notas fiscais emitidas e recebidas'

faturamento/forms.py
from django.forms import forms

from faturamento.models import Participante


class ParticipanteForm(forms.ModelForm):
    class Meta:
        model = Participante
        fields = ['cnpj_cpf', 'fisica_juridica', 'cep', 'razao_social', 'nome_fantasia', 'telefone', 'telefone2',
                  'celular', 'email', 'endereco', 'complemento', 'numero', 'bairro', 'cidade', 'estado',
                  'inscricao_estadual', 'inscricao_municipal']

faturamento/views.py
"""
    Participante - GENERIC VIEWS
"""

from django.contrib import messages
from django.contrib.admin.views import autocomplete
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.db.models import Q
from django.shortcuts import get_object_or_404, redirect, render
from django.views.generic import ListView, DetailView, CreateView, UpdateView

from faturamento.models import Participante




class ParticipanteList(SuccessMessageMixin, LoginRequiredMixin, ListView):
    model = Participante
    template_name = 'faturamento/participante/participante_list.html'

    def get_queryset(self):
        valor = self.request.GET.get('q')
        if valor:
            object_list = self.model.objects.filter(
                Q(razao_social__icontains=valor) |
                Q(nome_fantasia__icontains=valor) |
                Q(codigo__contains=valor) |
                Q(cnpj_cpf__contains=valor)
            )
        else:
            object_list = self.model.objects.all()

        paginator = Paginator(object_list, 7)  # Show 7 produtos per page

        page = self.request.GET.get('page')
        try:
            queryset = paginator.page(page)
        except PageNotAnInteger:
            # If page is not an integer, deliver first page.
            queryset = paginator.page(1)
        except EmptyPage:
            # If page is out of range (e.g. 9999), deliver last page of results.
            queryset = paginator.page(paginator.num_pages)

        # return object_list
        return queryset


class ParticipanteDetalhe(SuccessMessageMixin, LoginRequiredMixin, DetailView):
    model = Participante
    template_name = 'faturamento/participante/participante_detail.html'


class ParticipanteCreate(SuccessMessageMixin, LoginRequiredMixin, CreateView):
    model = Participante
    fields = '__all__'
    success_message = 'Registro criado com sucesso!'
    template_name = "faturamento/participante/participante_form.html"

    def get_success_message(self, cleaned_data):
        return self.success_message % dict(
            cleaned_data,
            calculated_field=self.object.id
        )


class ParticipanteUpdate(SuccessMessageMixin, LoginRequiredMixin, UpdateView):
    model = Participante
    fields = '__all__'
    success_message = 'Registro alterado com sucesso!'
    template_name = 'faturamento/participante/participante_form.html'

    def get_success_message(self, cleaned_data):
        return self.success_message % dict(
            cleaned_data,
            calculated_field=self.object.id
        )


def participante_delete(request, id=None):
    obj = get_object_or_404(Participante, id=id)
    if request.method == 'POST':
        obj.delete()
        messages.success(request, 'Registro apagado com sucesso!')
        return redirect('faturamento:participante_list')

    context = {
        'object': obj
    }

    return render(request, 'faturamento/confirm_delete.html', context)

faturamento/templates/faturamento/participante/participante_detail.html
{% extends 'materiais/base.html' %}

{% block content %}
<div class="col-md-offset-3">

    <!-- Histórico Padrão Info -->
    <h1>Razão Social: <strong><u>{{ participante.razao_social}}</u></strong></h1>
    <div class="col-sm-4 col-md-12">
        <div class="panel panel-default">
            <div class="panel-body" align="right">
                <a href="{% url 'faturamento:participante_list' %}">
                     <i class="fas fa-arrow-circle-left"></i> Voltar
                </a>
            </div>

            <h5>Nome Fantasia: <strong>{{ participante.nome_fantasia }}</strong></h5>
            <h5>Vendedor     : <strong>{{ participante.vendedor }}</strong></h5>
            <h5>Endereço     : <strong>{{ participante.endereco }}</strong></h5>
            <h5>Complemento  : <strong>{{ participante.exibe_complemento }}</strong></h5>
            <h5>Telefone 1   : <strong>{{ participante.telefone }}</strong></h5>
            <h5>Telefone 2   : <strong>{{ participante.exibe_telefone2 }}</strong></h5>
            <h5>Celular 1   : <strong>{{ participante.celular }}</strong></h5>
            <h5>Celular 2   : <strong>{{ participante.celular2 }}</strong></h5>
            <h5>E-mail       : <strong>{{ participante.exibe_email }}</strong></h5>
            <h5>Bairro       : <strong>{{ participante.exibe_bairro }}</strong></h5>
            <h5>Cidade       : <strong>{{ participante.cidade }}</strong></h5>
            <h5>Estado       : <strong>{{ participante.estado }}</strong></h5>
        </div>

    </div>

        {% if participante.pedidoweb_set.all %}
        <table class="responsive table table-responsive table-condensed table-bordered table-hover table-striped">
            <thead>
                <tr>
                    <th>Sequência</th>
                    <th>Descrição</th>
                    <th style="text-align:right">Preço Unitário</th>
                    <th style="text-align:right">Quantidade</th>
                    <th style="text-align:right">% Desconto</th>
                    <th style="text-align:right">Preço Líquido</th>
                </tr>
            </thead>

            <tbody>
                {% for item in clienteWeb.pedidoweb_set %}
                    <tr>
                        <td>{{ item.sequencia }}</td>
                        <td>{{ item.produto }}</td>
                        <td style="text-align:right">{{ item.preco_unitario|floatformat:2 }}</td>
                        <td style="text-align:right">{{ item.quantidade|floatformat:0 }}</td>
                        <td style="text-align:right">{{ item.perc_desc|floatformat:2 }}</td>
                        <td style="text-align:right">{{ item.total_produto|floatformat:2 }}</td>
                    </tr>
                {% endfor %}
            </tbody>

        </table>
    {% endif %}


</div>
{% endblock %}

faturamento/templates/faturamento/participante/participante_form.html
{% extends 'materiais/base.html' %}
{% load l10n %}

{% block content %}

<div class="col-md-offset-2"> <!-- Header -->
    <!-- Left Contato Info -->
    <div class="panel panel-default">
        <div class="panel-body">
            {% if participante.id %}
                <h4>Edita o Registro de {{participante.razao_social}}</h4>
            {% else %}
                <h4>Cria um Novo Cliente</h4>
            {% endif %}

            <div align="right">
                <a class="nav-link" href="{% url 'faturamento:participante_list' %}">
                     <i class="fas fa-arrow-circle-left"></i> Voltar
                </a>
            </div>
        </div>
    </div>


    <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {% include 'faturamento/form-template.html' %}
        <hr>
        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-4 btn-group">
                <button type="submit" class="btn btn-success">Gravar</button>
                <a href="{% url 'faturamento:participante_list' %}" class="btn btn-primary">Voltar</a>
            </div>

        </div>
    </form>

</div>


{% endblock %}

faturamento/templates/faturamento/participante/participante_list.html
{% extends 'materiais/base.html' %}
{% block participante_active %}active{% endblock %}

{% block content %}

<div class="container">

    <div class="card-group">

        <div class="card" align="center">
            <h5 style="margin-center"><strong>Lista de Clientes</strong></h5>
        </div>

        <div class="card" align="left">
             <!-- Pesquisa -->
            <form class="form-inline mt-2 mt-md-0">
                <input class="form-control mr-sm-2" id="searchbox" name="q" type="text" value="{{ request.GET.q }}" placeholder="Razão Social e CNPJ" aria-label="Search">
                <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Pesquisa <i class="fas fa-search"></i></button>
            </form>
        </div>



        <div class="card" align="center">
            <!-- pagination -->
            <nav aria-label="Page navigation example">
              <ul class="pagination pagination-sm justify-content-end">

                {% if object_list.has_previous %}
                <li class="page-item"><a class="page-link" href="?page={{ object_list.previous_page_number }}&q={{ request.GET.q }}"><i class="fas fa-chevron-circle-left"></i> Anterior</a></li>
                {% endif %}

                <li class="page-item active">
                    <span class="page-link">
                            Página {{ object_list.number }} de {{ object_list.paginator.num_pages }}
                            <span class="sr-only">(current)</span>
                    </span>
                </li>

                {% if object_list.has_next %}
                <li class="page-item"><a class="page-link" href="?page={{ object_list.next_page_number }}&q={{ request.GET.q }}"><i class="fas fa-chevron-circle-right"></i> Próxima</a></li>
                {% endif %}

              </ul>
            </nav>
            <!--end of pagination-->
        </div>

        <!--<div class="card" align="center">
         &lt;!&ndash; Botão Cria Registro &ndash;&gt;
            <a href="{% url 'faturamento:participante_add' %}">
                <button type="button" class="btn btn-success" data-toggle="tooltip"
                        title="Cria um novo registro"
                        style="margin-center: 4px;">
                    <i class="fas fa-plus-circle"></i>&nbsp; Cria Participante
                </button>
            </a>
        </div>-->

    </div>
    <!--end of card-group-->
</div>

<div class="container">
        {% if object_list %}
                    <div class="row">
                        {% for participante in object_list %}
                            <div class="col-sm-12">
                                <div class="card border-dark mb-3" style="background-color: #eee;">
                                    <div class="card-body">
                                        <h5 class="card-title">#{{ participante.codigo }} - Razão Social: {{ participante.razao_social}}</h5>
                                        <p class="card-text">Nome Fantasia: {{ participante.nome_fantasia }} - Tipo: {{ participante.exibe_fisica_juridica }}</p>
                                        <p class="card-text"> <i class="fas fa-phone-square"></i> {{ participante.telefone }} {% if participante.celular %} - <i class="fas fa-mobile-alt"></i> {{ participante.celular }}{%endif%}</p>
                                        <p class="card-text"> <i class="fas fa-map-marker-alt"></i></i> {{ participante.cidade }} - {{ participante.estado }}</p>

                                        <!-- Detalhes -->
                                        <a href="{% url 'faturamento:participante_detail' participante.id %}"
                                           class="btn btn-outline-primary btn-sm"><i class="fas fa-info-circle"></i> Detalhes</a>

                                        <!-- Altera -->
                                        <a href="{% url 'faturamento:participante_edit' participante.id %}"
                                            class="btn btn-outline-primary btn-sm" role="button" >
                                            <i class="fas fa-pencil-alt"></i>Edita
                                        </a>
                                    </div>
                                </div>
                            </div>
                        {% endfor %}
                    </div>

        {% else %}
            <h2>Nenhum registro encontrado para a pesquisa {{ request.GET.q }} </h2>
        <div align="right">
            <a class="nav-link" href="{% url 'faturamento:participante_list' %}">
                <i class="fas fa-arrow-circle-left"></i> Voltar
            </a>
        </div>
        {% endif %}
</div>
{% endblock %}